language: en
pipeline:
- name: CountVectorsFeaturizer
- name: WhitespaceTokenizer
  intent_tokenization_flag: true
  intent_split_symbol: +
- name: EmbeddingIntentClassifier
- name: SpacyNLP
  model: "en_loc"
- name: SpacyTokenizer
- name: RegexFeaturizer
- name: SpacyFeaturizer
  pooling: mean
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4
- name: SpacyEntityExtractor

policies:
- name: MemoizationPolicy
- name: KerasPolicy
- name: MappingPolicy
